name: Build and Push Custom LibreChat Image

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # Daily build at midnight UTC; adjust as needed.

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/librechat-custom:latest .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/librechat-custom:latest
